blueprint:
  name: Nordpool price based on 15min with time range
  description: |
    Käyttää Nordpool-integraatiota ja kytkee laitteita päälle pois
    halvimpiin 15 minuutin jaksoihin perustuen.
  domain: automation
  input:
    grid_area:
      name: Grid area sensor
      description: Tämä on Nordpoolin grid area -sensori
      selector:
        entity:
          domain:
          - sensor
          integration: nordpool
          multiple: false
    hour_rank:
      name: Hours on
      description: Montako tuntia (0–24) päivässä laite saa olla päällä
      default: 5
      selector:
        number:
          min: 0.0
          max: 24.0
          mode: slider
          step: 1.0
    min_hour:
      name: Earliest start hour
      description: Ensimmäinen kellonaika jolloin saa käynnistyä (0–23)
      default: 0
      selector:
        number:
          min: 0
          max: 23
          step: 1
    max_hour:
      name: Latest end hour
      description: Viimeinen kellonaika jolloin saa olla päällä (0–23)
      default: 23
      selector:
        number:
          min: 0
          max: 23
          step: 1
    allways_on:
      name: Always on price
      description: Jos hinta alle tämän, laite on aina päällä
      default: 0.0
      selector:
        number:
          min: 0.0
          max: 20.0
          mode: slider
          step: 0.1
    allways_off:
      name: Always off price
      description: Jos hinta yli tämän, laite on aina pois päältä
      default: 20
      selector:
        number:
          min: 0.0
          max: 60.0
          mode: slider
          step: 0.1
    turnon:
      name: TurnOn
      description: Toiminnot, jotka suoritetaan kun laite kytketään päälle
      default: []
      selector:
        action: {}
    turnoff:
      name: TurnOff
      description: Toiminnot, jotka suoritetaan kun laite kytketään pois päältä
      default: []
      selector:
        action: {}
variables:
  grid_area_var: !input grid_area
  hour_rank_var: !input hour_rank
  min_hour_var: !input min_hour
  max_hour_var: !input max_hour
  allways_on_var: !input allways_on
  allways_off_var: !input allways_off
trigger:
  - platform: time_pattern
    minutes: "/15"   # tarkistus jokaisella vartilla
action:
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {% set prices = state_attr(grid_area_var, 'today') %}
              {% if prices %}
                {% set h = now().hour %}
                {% set m = now().minute %}
                {% set idx = h * 4 + (m // 15) %}

                {# Suodatetaan kvartit aikahaarukkaan #}
                {% set filtered = [] %}
                {% for i in range(prices | count) %}
                  {% set p = prices[i] | float %}
                  {% set hour = i // 4 %}
                  {% if hour >= min_hour_var and hour < max_hour_var %}
                    {% set _ = filtered.append({'idx': i, 'price': p}) %}
                  {% endif %}
                {% endfor %}

                {% set allowed_quarters = hour_rank_var * 4 %}
                {% set sorted_filtered = filtered | sort(attribute='price') %}
                {% set cheapest = sorted_filtered[:allowed_quarters] | map(attribute='idx') | list %}

                {% set price_now = prices[idx] | float %}

                {{ (idx in cheapest or price_now <= (allways_on_var | float)) and (price_now < (allways_off_var | float)) }}
              {% else %}
                false
              {% endif %}
            
        sequence: !input turnon
    default: !input turnoff
